#Only mobs dying my a player will drop custom loot if set to True.
player_only: True

vanilla:
  #Plugin will ignore Vanilla mobs if set to False.
  enabled: True
  #Custom vanilla mob loot tables.
  skeleton:
    rare_items:
      - ADAMANTITE 50.0
      - SKELETON_DATA_CARD 0.1
    common_items:
      - INFERNAL_BONEMEAL 80.0
  zombie:
    rare_items:
      - MAGICAL_ZOMBIE_PILLS 10.0
    common_items:

mythic:
  #Plugin will regard Mythic Mobs as Vanilla mobs if set to False.
  enabled: False
  #Custom mythic mob loot tables.
  skeletalminion:
    rare_items:
      - CARBONADO 20.0
      - CARBON 80.0
    common_items: