#Only mobs dying my a player will drop custom loot if set to True.
player_only: True

vanilla:
  #Plugin will ignore Vanilla mobs if set to False.
  enabled: True
  #Custom vanilla mob loot tables.
  skeleton:
    #drop chances are calculated on a percentage.
    drops:
      - droptable:DropTableExample1 1-2 20.0
      - minecraft:bonemeal 5-10 50.0
  zombie:
    drops:
      - droptable:DropTableExample2 3-5 80.0

mythic:
  #Plugin will regard Mythic Mobs as Vanilla mobs if set to False.
  enabled: False
  #Custom mythic mob loot tables.
  skeletalminion:
    drops:
      - droptable:DropTableExample3 1 100.0