## CHANGE this to the name of your plugin.
name: SlimefunMobDrops

## CHANGE this to your username.
author: Antitonius

## CHANGE this to a meaninful but short description of your plugin.
description: My implementation of a Slimefun Mob Drop Table Addon.

## CHANGE this to the path of the class that extends JavaPlugin.
main: com.unipi.alexandris.slimefunaddon.slimefunmobdrops.SlimefunMobDrops

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://anthonyal.github.io

## This value is automatically replaced by the version specified in your pom.xml file.
## Do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.14

## This is required and marks Slimefun as a plugin dependency.
depend:
  - Slimefun
softdepend:
  - MythicMobs
commands:
  sfmobdrops:
    description: The command group for slimefun mod drops.
    aliases: sfmd
    permission: sfmobdrops
  permissions:
    sfmobdrops:
      description: Access to all Slimefun Mob Drops commands.
      default: op